### ISSUE TITLE
Support different highlight style

### ISSUE THREAD

**Issue by kongakong** [shuowu/jQuery-highlight#1]
I find this library rather useful. I would like it to support different highlight styles. Currently `jQuery-highlight-overlay` highlights a rectangular area. I have already made some changes such that it can 
- create a circular highlight area
- accept custom function to generate svg path for the highlight area.

Will you accept a PR?

**Comment by shuowu** [comment]
Sounds good! Can you submit the changes?

**Comment by kongakong** [comment]
Cool. I posted a PR https://github.com/shuowu/jQuery-highlight/pull/2
